const langEN = {
  mainTitle: "Ciudad de las Nubes",
  mainDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae leo id mi tempus congue.",
  timeline: [
    { id: "phase1", label: "Legends", title: "Legends", content: "Bohemundo has created the Sun for you. Alone, facing the Abyss, he drove the stars away from our land. Julia, Helion, Apopino; this new world, carved far from the abysmal darkness, is yours.", img: "imgs/etapas/leyenda.png" },
    { id: "phase2", label: "Conquest", title: "Conquest", content: "After the war against the angels, the descendants of Helion have claimed their ancestral right over humanity. Enock and his children lead the conquest with the blessing of the heavens, for all must be theirs.", img: "imgs/etapas/leyenda.png" },
    { id: "phase3", label: "Dominion", title: "Dominion", content: "The Heliones wither in the Ciudad de las Nubes, with the conquered lands at their feet. Now, the scientific revolution of the Gathai, the gold of the Medicit, and the forges of the Lennox threaten the hegemony of the Titan’s direct descendants.", img: "imgs/etapas/leyenda.png" },
    { id: "phase4", label: "Decline", title: "Decline", content: "The Imperial High Command has surrendered. The seams of the vast Empire, once Enock’s dream, unravel as his descendants lie forgotten on distant battlefields. No Helions remain in the City of Clouds, and in the chambers of grand palaces, visions of better worlds are dreamed.", img: "imgs/etapas/leyenda.png" },
    { id: "phase5", label: "Liberation", title: "Liberation", content: "The Ciudad de las Nubes has fallen. Julia, freed from her prison, has begun the conquest of her late brother’s ancient lands. Humanity breathes again, once more liberated from the curse of the Bent Soul imposed by the cruel heavens.", img: "imgs/etapas/leyenda.png" },
    { id: "phase6", label: "Total War", title: "Total War", content: "After centuries of reign, the Daughter of Bohemundo has been slain upon her throne. The sky has shattered, and the earth roars for the blood spilled. Has humanity condemned itself? Have they lost the favor of the heavens? Has the grace of the Sun abandoned them?", img: "imgs/etapas/leyenda.png" },
    { id: "phase7", label: "Celestial Towers", title: "Celestial Towers", content: "Under the shadow of the fractured sky, angels and humans were pardoned in the Council of Adrahan. United by the same destiny, they must hold the heavens strong; with the same strength that Bohemundo holds the Sun; with the same strength that Helion holds the Moon above our heads.", img: "imgs/etapas/leyenda.png" }
  ]
};
