const langES = {
  mainTitle: "CONCEPTO WEB",
  mainDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae leo id mi tempus congue.",
  timeline: [
    { id: "phase1", label: "Leyendas", title: "Leyendas", content: "Bohemundo ha creado para vosotros el Sol. Sólo, frente al Abismo, alejó a las estrellas de nuestra tierra. Julia, Helión, Apopino; vuestro es este nuevo mundo esculpido lejos de la oscuridad abismal.", img: "imgs/etapas/leyenda.png" },
    { id: "phase2", label: "Conquista", title: "Conquista", content: "Tras la guerra contra los ángeles, los descendientes de Helión han reclamado su derecho ancestral sobre la humanidad. Enock y sus hijos lideran la conquista con la bendición de los cielos, pues todo ha de ser suyo.", img: "imgs/etapas/leyenda.png" },
    { id: "phase3", label: "Dominio", title: "Dominio", content: "Los Heliones se marchitan en la Ciudad de las Nubes, con la tierra conquistada a sus pies. Ahora, la revolución científica de los Gathai, las monedas de los Medicit, y las fraguas de los Lennox amenazan la hegemonía de los descendientes directos del Titán.", img: "imgs/etapas/leyenda.png" },
    { id: "phase4", label: "Decadencia", title: "Decadencia", content: "El Alto Mando Imperial ha renunciado. Las costuras del vasto Imperio, que fue el sueño de Enock, se deshace mientras sus descendientes yacen olvidados en los lejanos campos de batalla. Ya no quedan Heliones en la Ciudad de las Nubes, y en las cámaras de los grandiosos palacios se sueñan mundos mejores. ", img: "imgs/etapas/leyenda.png" },
    { id: "phase5", label: "Liberación", title: "Liberación", content: "La Ciudad de las Nubes ha caído. Julia, liberada de su prisión, ha iniciado la conquista de las antiguas tierras de su difunto hermano. La humanidad respira de nuevo, liberada una vez más de la maldición del Alma Doblegada impuesta por los crueles cielos. ", img: "imgs/etapas/leyenda.png" },
    { id: "phase6", label: "Guerra Total", title: "Guerra Total", content: "Tras siglos de reinado, han asesinado a la Hija de Bohemundo en su trono. El cielo se ha partido, y la tierra ruge por la sangre derramada.  ¿Acaso la humanidad se ha condenado? ¿Perdieron el favor de los cielos? ¿Les abandonó la gracia del Sol? ", img: "imgs/etapas/leyenda.png" },
    { id: "phase7", label: "Torres Celestiales", title: "Torres Celestiales", content: "Bajo la sombra del cielo fracturado, ángeles y humanos fueron perdonados en el Concilio de Adrahan. Unidos por el mismo destino, deben sostener el cielo con fuerza; con la misma fuerza que Bohemundo sostiene el Sol; con la misma fuerza que Helión sostiene sobre nuestras cabezas la Luna", img: "imgs/etapas/leyenda.png" }
  ]
};